"""
Meta Analyzer — fixed version.

Bugs fixed:
 • calculate_consistency_score: `consistency_bonus` used in a conditional
   `locals()` check that silently failed when the list was empty →
   refactored to always set the variable.
 • np.var / np.mean called before checking list is non-empty.
 • Minor: `last_500_chars` assigned but never used in analyze_disclaimers.
"""

import re
import hashlib
import datetime
import math
import os
from collections import Counter
from typing import Any, Dict, List, Optional

import numpy as np


class MetaAnalyzer:

    def __init__(self):
        self.ai_tools_patterns = [
            r'chatgpt', r'gpt-3', r'gpt-4', r'openai', r'claude', r'bard',
            r'gemini', r'llama', r'copilot', r'perplexity',
            r'ai-generated', r'ai assisted', r'generated by ai', r'created with ai',
            r'this text was generated', r'as an ai', r'i am an ai', r"i'm an ai",
        ]
        self.template_patterns = [
            r'\[Your Name\]', r'\[Company Name\]', r'\[Date\]', r'\[Year\]',
            r'\[Insert.*?\]', r'\[.*?Placeholder.*?\]', r'Replace with.*?',
            r'Your [A-Z][a-z]+ Here', r'Enter [A-Z][a-z]+',
            r'\[\w+\s+\w+\]', r'\[[A-Z]+\]', r'\{[^}]+\}',
        ]
        self.document_sections = [
            'summary','objective','education','experience','skills',
            'projects','certifications','achievements','publications',
            'references','contact','profile','about','work history',
            'professional experience','technical skills','languages',
        ]
        self.ai_disclaimers = [
            'this response was generated','this text was generated',
            'as an ai language model','i do not have personal experiences',
            'i cannot provide','i am not able to','i do not have access to',
            'my training data','based on my training','according to my knowledge',
        ]
        self.ai_formatting = [
            r'•\s+\w+', r'\d+\.\s+\w+', r'##?\s+\w+',
            r'\*\*[^*]+\*\*', r'__[^_]+__', r'`[^`]+`', r'\|.*\|.*\|',
        ]
        self.human_indicators = [
            'draft','revision','edited','updated','version',
            'final','reviewed','approved','submitted',
        ]

    # ── main ─────────────────────────────────────────────────────────────────
    def analyze(self, text: str, filename: Optional[str] = None) -> Dict[str, Any]:
        if not text or len(text.strip()) < 50:
            return self._default(50.0)

        ai_tools_result  = self.detect_ai_tools(text)
        template_result  = self.detect_template_patterns(text)
        structure_score  = self.analyze_document_structure(text)
        disclaimer_score = self.analyze_disclaimers(text)
        formatting_score = self.analyze_formatting_patterns(text)
        fingerprints_score = self.analyze_digital_fingerprints(text, filename)

        meta_score = (
            ai_tools_result['score'] * 0.15 +
            template_result['score'] * 0.20 +
            structure_score          * 0.15 +
            disclaimer_score         * 0.20 +
            formatting_score         * 0.15 +
            fingerprints_score       * 0.15
        )

        return {
            'ai_tool_mentions':    ai_tools_result,
            'template_indicators': template_result,
            'document_structure':  round(structure_score, 2),
            'disclaimers':         round(disclaimer_score, 2),
            'formatting_patterns': round(formatting_score, 2),
            'digital_fingerprints':round(fingerprints_score, 2),
            'meta_score':          round(meta_score, 2),
            'details':             self._get_detailed_analysis(text, filename),
        }

    @staticmethod
    def _default(v):
        return {
            'ai_tool_mentions':    {'count':0,'density':0,'mentions':[],'score':v},
            'template_indicators': {'count':0,'density':0,'matches':[],'score':v},
            'document_structure':  v,
            'disclaimers':         v,
            'formatting_patterns': v,
            'digital_fingerprints':v,
            'meta_score':          v,
        }

    def _get_detailed_analysis(self, text: str, filename: Optional[str] = None) -> Dict[str, Any]:
        details = {
            'document_hash': hashlib.sha256(text.encode()).hexdigest()[:16],
            'char_count':    len(text),
            'word_count':    len(text.split()),
            'line_count':    len(text.split('\n')),
            'timestamps':    self._extract_timestamps(text),
            'has_disclaimer':any(
                re.search(p, text.lower()) for p in self.ai_disclaimers),
        }
        if filename:
            details['filename']  = filename
            details['extension'] = os.path.splitext(filename)[1].lower()
        return details

    def _extract_timestamps(self, text: str) -> Dict[str, Any]:
        date_patterns = [
            r'\b\d{1,2}/\d{1,2}/\d{2,4}\b',
            r'\b\d{4}-\d{2}-\d{2}\b',
            r'\b\d{1,2}-\d{1,2}-\d{2,4}\b',
            r'\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \d{1,2},? \d{4}\b',
            r'\b\d{1,2} (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \d{4}\b',
        ]
        dates_found = []
        for p in date_patterns:
            dates_found.extend(re.findall(p, text))

        cy = datetime.datetime.now().year
        future = past = recent = 0
        for d in dates_found:
            if str(cy) in d:         recent += 1
            elif any(str(y) in d for y in range(cy+1, cy+10)): future += 1
            elif any(str(y) in d for y in range(2000, cy)):     past   += 1

        years = re.findall(r'\b(19|20)\d{2}\b', text)
        return {
            'total_dates':   len(dates_found),
            'unique_dates':  len(set(dates_found)),
            'future_dates':  future,
            'past_dates':    past,
            'recent_dates':  recent,
            'years_mentioned': list(set(years)),
        }

    # ── sub-analyses ─────────────────────────────────────────────────────────
    def detect_ai_tools(self, text: str) -> Dict[str, Any]:
        tl = text.lower()
        mentions = [
            {'tool': m.group(), 'position': m.start()}
            for p in self.ai_tools_patterns
            for m in re.finditer(p, tl)
        ]
        cnt  = len(mentions)
        wc   = len(text.split()) or 1
        dens = (cnt / wc) * 1000

        score = 80 if cnt == 0 else 50 if cnt == 1 else 30 if cnt <= 3 else 20
        disc  = sum(1 for p in self.ai_disclaimers if re.search(p, tl))
        if disc > 0:
            score -= 10

        return {
            'count':   cnt,
            'density': round(dens, 2),
            'mentions':mentions[:5],
            'score':   round(max(0, min(100, score)), 2),
        }

    def detect_template_patterns(self, text: str) -> Dict[str, Any]:
        matches = [
            {'pattern': p, 'match': m.group(), 'position': m.start()}
            for p in self.template_patterns
            for m in re.finditer(p, text)
        ]
        cnt  = len(matches)
        wc   = len(text.split()) or 1
        dens = (cnt / wc) * 1000

        score = 90 if cnt == 0 else 60 if cnt == 1 else 40 if cnt <= 3 else 20
        name_ph = sum(1 for m in matches if 'Name' in m['match'] or 'NAME' in m['match'])
        date_ph = sum(1 for m in matches if 'Date' in m['match'] or 'DATE' in m['match'])
        if name_ph > 0 or date_ph > 0:
            score -= 20

        return {
            'count':                cnt,
            'density':              round(dens, 2),
            'matches':              matches[:5],
            'has_name_placeholder': name_ph > 0,
            'has_date_placeholder': date_ph > 0,
            'score':                round(max(0, min(100, score)), 2),
        }

    def analyze_document_structure(self, text: str) -> float:
        lines      = text.split('\n')
        paragraphs = [p for p in text.split('\n\n') if p.strip()]
        tl         = text.lower()

        headers = [sec for sec in self.document_sections
                   if re.search(r'(^|\n)' + re.escape(sec) + r'(\s*:|\s*$)',
                                tl, re.MULTILINE)]

        para_lens = [len(p.split()) for p in paragraphs]
        if para_lens:
            pm = float(np.mean(para_lens))
            ps = float(np.std(para_lens))
            para_cv = ps / pm if pm > 0 else 0
        else:
            para_cv = 0

        line_lens = [len(l) for l in lines if l.strip()]
        if line_lens:
            lm = float(np.mean(line_lens))
            ls = float(np.std(line_lens))
            line_cv = ls / lm if lm > 0 else 0
        else:
            line_cv = 0

        score = 70
        if   len(headers) > 8: score -= 15
        elif len(headers) > 5: score -= 5
        elif len(headers) < 2: score -= 5

        if   para_cv < 0.3: score -= 15
        elif para_cv > 1.0: score += 5
        if   line_cv < 0.2: score -= 10

        first_line = lines[0].lower() if lines else ''
        if any(s in first_line for s in ['dear','hi','hello','to whom','i am','my name is']):
            score += 10

        return round(max(0, min(100, score)), 2)

    def analyze_disclaimers(self, text: str) -> float:
        tl = text.lower()
        found = [
            {'text': m.group(), 'position': m.start()}
            for p in self.ai_disclaimers
            for m in re.finditer(re.escape(p), tl)
        ]
        cnt = len(found)
        end_disc = sum(1 for d in found if d['position'] > len(text) - 500)

        if   cnt == 0: score = 85
        elif cnt == 1: score = 40 if end_disc > 0 else 60
        elif cnt <= 3: score = 30
        else:          score = 20

        return round(max(0, min(100, score)), 2)

    def analyze_formatting_patterns(self, text: str) -> float:
        matches = [
            {'pattern': p, 'match': m.group(), 'position': m.start()}
            for p in self.ai_formatting
            for m in re.finditer(p, text, re.MULTILINE)
        ]
        cnt     = len(matches)
        bullets = sum(1 for m in matches if '•' in m['match'])
        nums    = sum(1 for m in matches if re.match(r'\d+\.', m['match']))
        unique  = len({m['pattern'] for m in matches})

        if   cnt == 0:  score = 80
        elif cnt < 5:   score = 70
        elif cnt < 10:  score = 60 if unique > 2 else 45
        else:
            if   bullets > cnt * 0.7: score = 30
            elif nums    > cnt * 0.7: score = 35
            else:                     score = 40

        return round(max(0, min(100, score)), 2)

    def analyze_digital_fingerprints(self, text: str,
                                      filename: Optional[str] = None) -> float:
        score = 70
        tl    = text.lower()

        non_ascii = re.findall(r'[^\x00-\x7F]+', text)
        score -= min(20, len(non_ascii) * 2)

        double_spaces = re.findall(r' {2,}', text)
        score -= min(10, len(double_spaces))

        tab_count = text.count('\t')
        score -= 10 if tab_count > 10 else (5 if tab_count > 0 else 0)

        line_lens = [len(l) for l in text.split('\n') if l.strip()]
        if line_lens:
            lc = Counter(line_lens)
            dup = sum(1 for c in lc.values() if c > 1)
            if dup > len(line_lens) * 0.3:
                score -= 15

        if filename:
            ext = os.path.splitext(filename)[1].lower()
            if ext not in ['.txt','.docx','.pdf','.rtf','.md']:
                score -= 5
            if any(ind in filename.lower() for ind in ['ai-','generated','chatgpt','gpt']):
                score -= 20

        human_cnt = sum(1 for ind in self.human_indicators if ind in tl)
        score += min(15, human_cnt * 3)

        return round(max(0, min(100, score)), 2)

    # ── consistency helper ────────────────────────────────────────────────────
    def calculate_consistency_score(self, text: str) -> float:
        scores = [
            self.detect_ai_tools(text)['score'],
            self.detect_template_patterns(text)['score'],
            self.analyze_document_structure(text),
            self.analyze_disclaimers(text),
            self.analyze_formatting_patterns(text),
            self.analyze_digital_fingerprints(text),
            self.analyze_timestamps(text)['score'],
        ]
        if not scores:
            return 50.0

        mean_score = float(np.mean(scores))
        variance   = float(np.var(scores))      # ← FIX: was inside conditional with broken locals()

        consistency_bonus = -10 if variance < 100 else (0 if variance < 300 else 10)
        return round(mean_score + consistency_bonus, 2)

    def analyze_timestamps(self, text: str) -> Dict[str, Any]:
        data = self._extract_timestamps(text)
        if   data['total_dates'] == 0:    score = 70
        elif data['future_dates'] > 0:    score = 30
        elif (data['recent_dates'] > data['past_dates'] * 2): score = 45
        elif (data['past_dates']   > data['recent_dates'] * 2): score = 85
        else:                             score = 65

        if (data['unique_dates'] < data['total_dates'] * 0.5
                and data['total_dates'] > 0):
            score -= 15

        return {'score': round(score, 2), 'details': data}
